# MODEL
net: vit_small # choose among [simclr]
backbone_name: vit_small

# DIRECTORIES
checkpoint_dir: /homes/nmorelli/aibio_nico/checkpoint
dataset_dir: /work/ai4bio2024/rxrx1
load_checkpoint: ~
load_backbone: ~
metadata_path: /work/h2020deciderficarra_shared/rxrx1/metadata/m_3c_experiment_strat.csv

# TRAINING OPTIONS
epochs: 50
batch_size: 64
loss: simclrloss # choose among [simclrloss, ce]
opt: adamW # choose among [adam,]
sched: poly # [onecycle, poly, CosineAnnealingWarmRestarts]
lr: 0.0005
evaluation_freq: 4
model_save_freq: 10
sched_pow: 1
num_classes: 4
sampler: False
dataset_norm: True

# HARDWARE
device: gpu
multiple_gpus: True
train_workers: 16
evaluation_workers: 16

# WNADB CONFIG
project_name: "aibio_prj"
run_name: "dino_base_poly"
